In [1]:
import tskit
import numpy as np
import gaiapy as gp
import pandas as pd
from scipy.spatial.distance import pdist, squareform
from tqdm import tqdm

In [ ]:

listed = {0.2, 0.5, 1.1, 1.4, 1.7, 2.0} # excluding 0.8 bc i didnt realize i only had two of them not four like the rest 

suffixes = ['child_results', 'node_stats', 'parent_results', 'static_info', 'unary_results']

data = {}

for i in listed:
    data[i] = {} 
    for j in range(4):
        data[i][j] = {}
        
        for suffix in suffixes:
        
            file_path = f"output/S{i}-R{j}__{suffix}.csv"
            

  
            data[i][j][suffix] = pd.read_csv(file_path)
          

# Example: How to access the 'node_stats' for S0.2, R0
# df = data[0.2][0]['node_stats']
          

# Example: How to access the 'node_stats' for S0.2, R0
# df = data[0.2][0]['node_stats']



S0_2_unary = pd.concat([data[0.2][j]['unary_results'] for j in range(4)], ignore_index=True)

S1_1_unary = pd.concat([data[1.1][j]['unary_results'] for j in range(4)], ignore_index=True)

In [3]:
s11_0 = tskit.load("tree-files/tree-S1.1-R0.trees")
s11_1 = tskit.load("tree-files/tree-S1.1-R1.trees")
# s11_2 = tskit.load("tree-files/tree-S1.1-R2.trees")
# s11_3 = tskit.load("tree-files/tree-S1.1-R3.trees")

# s02_0 = tskit.load("tree-files/tree-S0.2-R0.trees")
# s02_1 = tskit.load("tree-files/tree-S0.2-R1.trees")
# s02_2 = tskit.load("tree-files/tree-S0.2-R2.trees")
# s02_3 = tskit.load("tree-files/tree-S0.2-R3.trees")

sts_110 = s11_0.simplify()
sts_111 = s11_1.simplify()
# sts_112 = s11_2.simplify()
# sts_113 = s11_3.simplify()

# sts_020 = s02_0.simplify()
# sts_021 = s02_1.simplify()
# sts_022 = s02_2.simplify()
# sts_023 = s02_3.simplify()

ets_110 = sts_110.extend_haplotypes()
ets_111 = sts_111.extend_haplotypes()
# ets_112 = sts_112.extend_haplotypes()
# ets_113 = sts_113.extend_haplotypes()

# ets_020 = sts_020.extend_haplotypes()
# ets_021 = sts_021.extend_haplotypes()
# ets_022 = sts_022.extend_haplotypes()
# ets_023 = sts_023.extend_haplotypes()

In [5]:
highest_error_diff = (data[1.1][0]['unary_results']['unary_sts_error'] - data[1.1][0]['unary_results']['unary_ets_error']).nlargest(10).index
result_high_s110 = data[1.1][0]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[1.1][1]['unary_results']['unary_sts_error'] - data[1.1][1]['unary_results']['unary_ets_error']).nlargest(10).index
result_high_s111 = data[1.1][1]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[1.1][2]['unary_results']['unary_sts_error'] - data[1.1][2]['unary_results']['unary_ets_error']).nlargest(10).index
result_high_s112 = data[1.1][2]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[1.1][3]['unary_results']['unary_sts_error'] - data[1.1][3]['unary_results']['unary_ets_error']).nlargest(10).index
result_high_s113 = data[1.1][3]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')


highest_error_diff = (data[0.2][0]['unary_results']['unary_sts_error'] - data[0.2][0]['unary_results']['unary_ets_error']).nlargest(10).index
result_high_s020 = data[0.2][0]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[0.2][1]['unary_results']['unary_sts_error'] - data[0.2][1]['unary_results']['unary_ets_error']).nlargest(10).index
result_high_s021 = data[0.2][1]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[0.2][2]['unary_results']['unary_sts_error'] - data[0.2][2]['unary_results']['unary_ets_error']).nlargest(10).index
result_high_s022 = data[0.2][2]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[0.2][3]['unary_results']['unary_sts_error'] - data[0.2][3]['unary_results']['unary_ets_error']).nlargest(10).index
result_high_s023 = data[0.2][3]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

In [5]:
highest_error_diff = (data[1.1][0]['unary_results']['unary_sts_error'] - data[1.1][0]['unary_results']['unary_ets_error']).nsmallest(10).index
result_low_s110 = data[1.1][0]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[1.1][1]['unary_results']['unary_sts_error'] - data[1.1][1]['unary_results']['unary_ets_error']).nsmallest(10).index
result_low_s111 = data[1.1][1]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[1.1][2]['unary_results']['unary_sts_error'] - data[1.1][2]['unary_results']['unary_ets_error']).nsmallest(10).index
result_low_s112 = data[1.1][2]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[1.1][3]['unary_results']['unary_sts_error'] - data[1.1][3]['unary_results']['unary_ets_error']).nsmallest(10).index
result_low_s113 = data[1.1][3]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')


highest_error_diff = (data[0.2][0]['unary_results']['unary_sts_error'] - data[0.2][0]['unary_results']['unary_ets_error']).nsmallest(10).index
result_low_s020 = data[0.2][0]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[0.2][1]['unary_results']['unary_sts_error'] - data[0.2][1]['unary_results']['unary_ets_error']).nsmallest(10).index
result_low_s021 = data[0.2][1]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[0.2][2]['unary_results']['unary_sts_error'] - data[0.2][2]['unary_results']['unary_ets_error']).nsmallest(10).index
result_low_s022 = data[0.2][2]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

highest_error_diff = (data[0.2][3]['unary_results']['unary_sts_error'] - data[0.2][3]['unary_results']['unary_ets_error']).nsmallest(10).index
result_low_s023 = data[0.2][3]['unary_results'].loc[highest_error_diff].set_index('unary_node_id')

result_high_s110.head()

,unary_node_time,unary_sts_error,unary_ets_error,unary_dist_from_sample_centroid0,unary_sts_dist_from_sample_centroid,unary_ets_dist_from_sample_centroid,added_span,wrongly_added_span,sts_span,ets_span
unary_node_id,,,,,,,,,,
9686.0,1499.0,3.337057,2.683704,145.691264,66.393836,16.510052,445094.0,0.0,130826.0,575920.0
9713.0,1603.0,3.788693,3.248023,127.752326,108.403967,40.827080,192256.0,0.0,166127.0,358383.0
9719.0,1631.0,3.769273,3.236542,129.899139,103.500825,37.259305,786249.0,0.0,810722.0,1596971.0
9695.0,1525.0,3.594787,3.064868,130.188616,101.259978,37.307104,477429.0,43040.0,224980.0,702409.0
9733.0,1708.0,3.562944,3.039081,115.196785,80.150596,14.983894,341348.0,0.0,39173.0,380521.0

In [9]:
result_high_s111.head()

,unary_node_time,unary_sts_error,unary_ets_error,unary_dist_from_sample_centroid0,unary_sts_dist_from_sample_centroid,unary_ets_dist_from_sample_centroid,added_span,wrongly_added_span,sts_span,ets_span
unary_node_id,,,,,,,,,,
12108.0,970.0,0.167213,0.078025,125.260762,73.470020,122.531827,1754654.0,378495.0,126552.0,1881206.0
12604.0,5980.0,0.208082,0.129621,89.546716,16.258386,35.369619,3994381.0,0.0,1338906.0,5333287.0
12531.0,5447.0,0.243875,0.171110,40.241639,18.331441,52.173079,2012434.0,44840.0,29081.0,2041515.0
12594.0,5895.0,0.210741,0.138432,94.704531,18.054263,34.838398,4135349.0,2481837.0,38716.0,4174065.0
12580.0,5788.0,0.182181,0.111360,99.015633,17.105028,26.049291,4019434.0,2433255.0,560348.0,4579782.0

In [10]:
result_low_s110.head()

,unary_node_time,unary_sts_error,unary_ets_error,unary_dist_from_sample_centroid0,unary_sts_dist_from_sample_centroid,unary_ets_dist_from_sample_centroid,added_span,wrongly_added_span,sts_span,ets_span
unary_node_id,,,,,,,,,,
9428.0,660.0,1.554420,2.289568,199.204139,169.004019,76.761991,1839413.0,0.0,45940.0,1885353.0
9483.0,797.0,2.053091,2.564071,168.208486,91.466629,28.359534,554860.0,0.0,621147.0,1176007.0
9241.0,398.0,1.652730,2.127328,179.648042,168.696567,108.030669,5018196.0,0.0,177185.0,5195381.0
9435.0,681.0,2.092907,2.543103,189.727805,93.503414,37.013025,139795.0,0.0,368174.0,507969.0
9436.0,683.0,2.092548,2.510508,191.672269,90.029252,37.898979,187605.0,0.0,214224.0,401829.0

In [11]:
result_low_s111.head()

,unary_node_time,unary_sts_error,unary_ets_error,unary_dist_from_sample_centroid0,unary_sts_dist_from_sample_centroid,unary_ets_dist_from_sample_centroid,added_span,wrongly_added_span,sts_span,ets_span
unary_node_id,,,,,,,,,,
12226.0,1208.0,0.210742,0.349873,202.669984,149.072631,72.521035,4926799.0,52216.0,815304.0,5742103.0
12338.0,2556.0,0.061518,0.197209,132.403923,87.209930,23.624862,3435187.0,933357.0,643803.0,4078990.0
12316.0,1953.0,0.087524,0.203780,137.922457,79.197587,28.319035,29596.0,0.0,3636.0,33232.0
12232.0,1253.0,0.213137,0.329021,203.117332,149.888738,103.424240,297230.0,0.0,346577.0,643807.0
12339.0,2559.0,0.064974,0.175495,132.649043,85.908252,33.915358,2035533.0,1247641.0,555230.0,2590763.0

In [17]:
s110_wrong_avg = result_high_s110['wrongly_added_span'].mean()
s111_wrong_avg = result_high_s111['wrongly_added_span'].mean()
print(s110_wrong_avg)
print(s111_wrong_avg)

4304.0
696198.8

In [15]:
target_node_ids = result_high_s110.index.tolist()
# for n in target_node_ids:
#     print(data[1.1][1]['node_stats']['num_parents'][n])

def count_trees_with_node(ts, node_id):
    count = 0
    id = int(node_id)
    for tree in ts.trees():
        # A node is in a tree if it is not isolated.
        # This checks if it has a parent or at least one child.
        if not tree.is_isolated(id):
            count += 1
    return count

sts_list = []
ets_list = []
for id in target_node_ids:
    sts_list.append(count_trees_with_node(sts_110, id))
    ets_list.append(count_trees_with_node(ets_110, id))
print(sts_list)
print("")
print(ets_list)
print("")

diff_list = np.arange(10)
for j in np.arange(10):
    diff_list[j] = ets_list[j] - sts_list[j]
print(diff_list)

[21, 17, 113, 28, 6, 4, 56, 29, 180, 9]

[93, 43, 228, 84, 56, 81, 151, 81, 392, 203]

[ 72  26 115  56  50  77  95  52 212 194]

In [14]:
target_node_ids = result_high_s111.index.tolist()
# for n in target_node_ids:
#     print(data[1.1][1]['node_stats']['num_parents'][n])

sts_list = []
ets_list = []
for id in target_node_ids:
    sts_list.append(count_trees_with_node(sts_111, id))
    ets_list.append(count_trees_with_node(ets_111, id))
print(sts_list)
print("")
print(ets_list)
print("")
diff_list = np.arange(10)
for j in np.arange(10):
    diff_list[j] = ets_list[j] - sts_list[j]
print(diff_list)

[24, 235, 9, 5, 94, 32, 194, 54, 203, 65]

[333, 890, 315, 723, 801, 262, 648, 333, 343, 307]

[309 655 306 718 707 230 454 279 140 242]

In [18]:
max = data[1.1][0]['unary_results']['unary_ets_error'].max()
print(max)
max2 = data[1.1][0]['unary_results']['unary_sts_error'].max()
print(max2)
max3 = data[1.1][1]['unary_results']['unary_ets_error'].max()
print(max3)
max4 = data[1.1][1]['unary_results']['unary_sts_error'].max()
print(max4)
print("max")
print("")

min = data[1.1][0]['unary_results']['unary_ets_error'].min()
print(min)
min2 = data[1.1][0]['unary_results']['unary_sts_error'].min()
print(min2)
min3 = data[1.1][1]['unary_results']['unary_ets_error'].min()
print(min3)
min4 = data[1.1][1]['unary_results']['unary_sts_error'].min()
print(min4)
print("min")
print("")

avg = data[1.1][0]['unary_results']['unary_ets_error'].mean()
print(avg)
avg2 = data[1.1][0]['unary_results']['unary_sts_error'].mean()
print(avg2)
avg3 = data[1.1][1]['unary_results']['unary_ets_error'].mean()
print(avg3)
avg4 = data[1.1][1]['unary_results']['unary_sts_error'].mean()
print(avg4)
print("avg")

4.514901247022313
4.513611965767933
0.8187794530463587
0.8176644224207484
max

0.7785268514007437
0.7802905354609685
0.0008326592331602
0.0005624371561744
min

2.9246255359734725
2.927724184644383
0.29706740267704246
0.29617699375386947
avg

(simp and ets num trees and num nodes are the same )
(proportion = num extended/total)

tree S1.1 R0 - very splatty and wide 
 - number of trees                 38089
 - simp num trees                  13760
 - num nodes                       761,351
 - simp num nodes                  10000
 - num extended nodes              7,348
 - proportion extended             0.7348
 - mean extension                  16,944,903.62642896
 - mean wrong extension            552,690.6686173108
 - number extended incorrectly     1203
 - proportion extended incorrectly 0.16371801850843767
 
tree S1.1 R1  - very narrow error difference - concentrated around 0 
 - number of trees                 45421
 - simp num trees                  17262
 - num nodes                       679,426
 - simp num nodes                  12711
 - num extended nodes              9,478
 - proportion extended             0.7456533710959012
 - mean extension                  16,949,358.25437856
 - mean wrong extension            644,112.8978687486
 - number extended incorrectly     1755
 - proportion extended incorrectly 0.18516564676092004
 
tree S1.1 R2 medium spread apart 
 - number of trees                 38575
 - simp num trees                  11390
 - num nodes                       736678
 - simp num nodes                  8296
 - num extended nodes              6414
 - proportion extended             0.7731436837029894
 - mean extension                  15227824.64094169
 - mean wrong extension            571982.3932023698
 - number extended incorrectly     1359
 - proportion extended incorrectly 0.2118802619270346

tree S1.1 R3 very splatty and bright at young times - lots of variation 
 - number of trees                 48748
 - simp num trees                  16689
 - num nodes                       831717
 - simp num nodes                  12163
 - num extended nodes              9113
 - proportion extended             0.7492394968346625
 - mean extension                  16615051.242620433
 - mean wrong extension            637566.1259738834
 - number extended incorrectly     1724
 - proportion extended incorrectly 0.1891802918907056


 differences in number of trees is 5872 ( max number of trees is 5872 more than smallest number of trees )
 much more variety in number of trees , 0.2 is more consistent 




tree S0.2 R0 
 - number of trees                 38006
 - simp num trees                  10756
 - num nodes                       722000
 - simp num nodes                  7929
 - num extended nodes              5864
 - proportion extended             0.739563627191323
 - mean extension                  15527364.318042291
 - mean wrong extension            634230.1792291951
 - number extended incorrectly     1201
 - proportion extended incorrectly 0.20480900409276945

tree S0.2 R1 
 - number of trees                 39622
 - simp num trees                  12570
 - num nodes                       674885
 - simp num nodes                  9016
 - num extended nodes              6781
 - proportion extended             0.7521073646850044
 - mean extension                  15747266.52956791
 - mean wrong extension            629520.8305559652
 - number extended incorrectly     1389
 - proportion extended incorrectly 0.20483704468367497

tree S0.2 R2
 - number of trees                 39941
 - simp num trees                  15274
 - num nodes                       692822
 - simp num nodes                  11088
 - num extended nodes              8321
 - proportion extended             0.750450937950938
 - mean extension                  16315032.054801106
 - mean wrong extension            547054.3590914553
 - number extended incorrectly     1463
 - proportion extended incorrectly 0.17582021391659655

tree S0.2 R3
 - number of trees                 45679
 - simp num trees                  16345
 - num nodes                       790105
 - simp num nodes                  11921
 - num extended nodes              9007
 - proportion extended             0.755557419679557
 - mean extension                  16124130.481625402
 - mean wrong extension            614566.7755079382
 - number extended incorrectly     1802
 - proportion extended incorrectly 0.20006661485511268



  differences in number of trees is 5589 ( max number of trees is 5589 more than smallest number of trees )
  more consistent, like more around 13-16k ?

Ones with high error change between replicates (loosely ranked)
    - 1.1
    - 1.7
    - 0.5

ones with medium error change between replicates (not ranked)
    - 0.2
    - 0.8
    - 1.4
    - 2.0



investigate examples with high error change between replicates - some examples dont change mucg bw replicates some do 
compare like proportions of nodes that were extended and by how much between examples both replicates and other sigmas 
threshold nodes that were extended the most and nodes with the highest difference in error 
    - did they have error in extension? how much extended? lots of parents not lots of parents? lots of children not lots of children? 
    how many trees did it get extended into?

think more about how gaia actually works when were doing this 


something in the arg itself thats happening that we have to figure out 


get data on number of trees its in before and post extension